apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-consumer
  template:
    metadata:
      labels:
        app: task-consumer
    spec:
      containers:
        - name: task-consumer
          image: task-consumer
          imagePullPolicy: Never
          env:
            - name: POSTGRES_CONNECTION_STRING
              value: "host=postgres-service dbname=taskdb user=taskuser password=taskpassword sslmode=disable"
